### PR TITLE
Separated core implementation and example code

### PR DESCRIPTION
**Pull request by johkin**
This could be an start for a separated jar-file that could be used as a maven/gradle dependency.

I haven't tried the release process, so there might be surprises to find.

### CODE REVIEW

**Comment by danbell** [comment]
+1

**Comment by ramswaroop** [comment]
Hi @johkin, thanks very much for the pull request. Very excited to see the first PR. After you raised the issue yesterday I was also thinking the same and you did it. Cheers 👍 . Will verify and merge.

**Comment by johkin** [comment]
In the example code, you need to add:
@SpringBootApplication(scanBasePackages = {"org.myorg.mybot",
        "me.ramswaroop.jbot.slackbot.core"})
Otherwise it seems to work.
Maybe you should change the package name of the example code, so that it is obvious that you need to specify your own basepackage in the annotation?

**Comment by ramswaroop** [comment]
@johkin Just FYI: You can also make the required changes and commit to your fork, it will automatically be included in this pull request.

**Comment by ramswaroop** [comment]
@johkin Hey I merged your PR but your name isn't listed under contributions tab, any idea?

**Comment by johkin** [comment]
No worries about the contributor-details! I only moved some of the code, you've done all the work!

**Comment by ramswaroop** [comment]
@johkin That's nice of you but I am curious to know the reason behind it. Btw your changes are now released to Maven Central and will be available to everyone within few minutes. Thanks for contributing :)

**Comment by ramswaroop** [comment]
@johkin I finally figured out why your name wasn't shown as a contributor. Your github email and the email from which you committed were probably different. That's why it didn't show up as a contributor.

**Pull request merged**
